version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: grooming_service
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: redis_cache
    restart: unless-stopped
    ports:
      - "6379:6379"

  grooming-service:
    build: ./grooming_service
    container_name: grooming-service
    restart: unless-stopped
    ports:
      - "8002:8002"
    depends_on:
      - db
      - redis
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: grooming_service
      DB_USERNAME: root
      DB_PASSWORD: root
      QUEUE_CONNECTION: redis
      REDIS_HOST: redis
      REDIS_PORT: 6379

volumes:
  db_data: